@startuml

start

:Запуск приложения;
:Загрузка информации из базы данных;
:Инициализация SharedAppEventsViewModel;

if (База данных корректна?) then (да)
  :Показать главный экран;
else (нет)
  :Показать ошибку или резервный экран;
  stop
endif

repeat
  :Отобразить статистику БД и действия;

  if (Пользователь выбрал "Просмотр записей") then (да)
    :Загрузить последние записи;
    :Показать список записей;

    if (Пользователь выбрал запись) then (да)
      :Загрузить EntryWithRecording;
      :Показать детали;

      if (Пользователь редактирует описание) then (да)
        :Загрузить запись;
        :Пользователь редактирует описание;
        :Пользователь добавляет/удаляет изображения;

        if (Пользователь сохраняет) then (да)
          :UpdateEntryUseCase;
          :Сгенерировать событие EntryChanged;
        endif
      endif

      if (Пользователь удаляет запись) then (да)
        :DeleteEntryUseCase;
        :Сгенерировать событие EntryChanged;
      endif
    endif

  else (нет)
    if (Пользователь выбрал "Поиск") then (да)
      :Загрузить фильтры;
      :Пользователь выбирает фильтры;
      :Сформировать SearchQuery;
      :SearchEntriesUseCase;
      :Показать результаты;

      if (Пользователь выбрал запись) then (да)
        :Загрузить EntryWithRecording;
        :Показать детали;
      endif

    else (нет)
      if (Пользователь выбрал "Создать новую запись") then (да)
        :Загрузить справочные данные;
        :Пользователь выбирает метаданные;
        :Пользователь вводит заголовок;

        if (Пользователь добавляет новые справочные данные) then (да)
          :Добавить Year/Brand/Model/Location;
          :Перезагрузить списки;
        endif

        :CreateEntryUseCase;
        :Загрузить запись;
        :Пользователь редактирует описание;

        if (Пользователь сохраняет) then (да)
          :UpdateEntryUseCase;
          :Сгенерировать событие EntryChanged;
        endif

      else (нет)
        if (Пользователь выбрал "Настройки") then (да)
          :Загрузить настройки;

          if (Пользователь экспортирует БД) then (да)
            :ExportDatabaseUseCase;
            :Показать прогресс экспорта;
          endif

          if (Пользователь объединяет БД) then (да)
            :MergeJsonDatabaseUseCase;
            :Показать прогресс объединения;
            :Сгенерировать событие DatabaseMerged;
          endif

          if (Пользователь меняет тему) then (да)
            :Сохранить тему в DataStore;
          endif

        else (нет)
          if (Пользователь выбрал "О программе") then (да)
            :Показать информацию о версии;
          else (нет)
            break
          endif
        endif
      endif
    endif
  endif

repeat while (Пользователь остаётся на главном экране?)

stop

@enduml